--Q1 What is the total revenue generated by male and Female

SELECT gender, sum(purchase_amount) as total_revenue
from customers
GROUP by gender;

 --Q2 Which customers used a discount coupon but still spent more than average purchase amount?
 
 SELECT customer_id, purchase_amount
 FROM customers
 WHERE discount_applied = 'Yes' and purchase_amount > (SELECT avg(purchase_amount) from customers)
 
 --Q3 Which are the top 5 products with the highest average ratings?
 
 SELECT item_purchased, round(AVG(review_rating),2) as "Average Product Rating"
 from customers
 GROUP BY item_purchased
 ORDER by AVG(review_rating) desc LIMIT 5;
 
 --Q4 Compare the Average Purchase Amounts betweeen Standard and Express Shipping. 
 
 SELECT shipping_type, round(avg(purchase_amount),2) as "Average Purchase Amount"
 FROM customers
 WHERE shipping_type = 'Express' or shipping_type = 'Standard'
 GROUP BY shipping_type;
 
 --Q5 Do subscribed customer spend more? Compare average spent and total revenue between subscribed and non subcribed customer.customers
 
 SELECT 
 COUNT(customer_id) as 'Total Customers',
 subscription_sta, round(AVG(purchase_amount),2) as 'Average Spent', sum(purchase_amount) as 'Total Revenue'
 from customers
 GROUP by subscription_sta
 order By sum(purchase_amount);

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
 
 SELECT item_purchased, 
 ROUND(100.0 * SUM(CASe when discount_applied = 'Yes' then 1 else 0 end)/count(*) ,2) as discount_percentage 
 from customers
 GROUP BY item_purchased 
 ORDER By discount_percentage DESC
 limit 5;
 
-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

SELECT 
    SUM(CASE WHEN previous_purchas = 1 THEN 1 ELSE 0 END) AS New_Customers,
    SUM(CASE WHEN previous_purchas BETWEEN 2 AND 10 THEN 1 ELSE 0 END) AS Returning_Customers,
    SUM(CASE WHEN previous_purchas > 10 THEN 1 ELSE 0 END) AS Loyal_Customers
FROM customers;

--Q8. What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 
  SELECT 
  subscription_sta,
  COUNT(*) as repeated_buyers
  FROM
  customers
  GROUP BY subscription_sta
  HAVING previous_purchas > 5 ;
 
 --Q10. What is the revenue contribution of each age group? 
 
 SELECT age_group,
 sum(purchase_amount) as revenue_generated
 from customers
 GROUP by age_group 
 ORDER by revenue_generated desc;
 
 
 
 
 
